name: confirm_exit_dialog
description: The project demonstrates how to present a dialog to let the users to confirm if they really want to exit current app, when they tap on the back button on Android.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
